services:
  db:
    image: postgres:15
    container_name: neotech-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: neotech

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: ["./entrypoint.sh"]

volumes:
  postgres_data:
